# hugo server --minify --themesDir ... --baseURL=http://localhost:1313/theme/book/

baseURL = 'https://docs.gerillass.com/'
title = 'Gerillass Documentation'

# Book configuration
disablePathToLower = true
# enableGitInfo = true

# This command below is cleaning the unused content of ./public folder.
cleanDestinationDir = true

# Needed for mermaid/katex shortcodes

[markup]
[markup.goldmark.renderer]
    unsafe = true
    
[markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "dracula"
    tabWidth = 2

    # Theme Names: "abap", "arduino", "borland", "bw", "colorful", "dracula", "fruity", "github", "igor", "manni", "monokai", "monokailight", "murphy", "native", "paraiso-dark", "paraiso-light", "perldoc", "solarized-dark", "solarized-dark256", "solarized-light", "solarized-light", "tango", "trac", "vs", "xcode"

[markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5

[params]
    Description = "Gerillass is an open-source Sass library built on top of Sass to help designers and developers rapidly-produce consistent and scalable CSS outputs regardless of the size of the projects they are working on, aiming to make these processes easy and fun."

    Keywords = "Gerillass, CSS, CSS3, Web Design, Sass Mixins, Sass Functions, SCSS, Sass, Sass Toolkit, Sass Library, Sass Libraries, Sass Framework, Learn Sass, What is Sass, Frontend Tools"

    # (Optional, default true) Controls table of contents visibility on right side of pages.
    # Start and end levels can be controlled with markup.tableOfContents setting.
    # You can also specify this parameter per page in front matter.
    # BookToC = true

    BookTocLabel = "Table of Contents"
    # (Optional, default none) Set the path to a logo for the book. If the logo is
    # /static/logo.png then the path would be logo.png
    LogoLink = 'images/gerillass-logo.svg'
    # LogoTitle = "Gerillass Documentation"
    
    # (Optional, default none) Set leaf bundle to render as side menu
    # When not specified file structure and weights will be used
    #   BookMenuBundle = '/menu'

    # (Optional, default docs) Specify section of content to render as menu
    # You can also set value to '*' to render all sections to menu
    BookSection = "docs"

    # Set source repository location.
    # Used for 'Last Modified' and 'Edit this page' links.
    BookRepo = 'https://github.com/selfishprimate/gerillass-docs'

    # Enable "Edit this page" links for 'doc' page type.
    # Disabled by default. Uncomment to enable. Requires 'BookRepo' param.
    # Path must point to 'content' directory of repo.
    BookEditPath = 'tree/master/content'

    # Configure the date format used on the pages
    # - In git information
    # - In blog posts
    BookDateFormat = 'Jan 2, 2006'

    # (Optional, default true) Enables search function with flexsearch,
    # Index is built on fly, therefore it might slowdown your website.
    # BookSearch = true

    # (Optional, default true) Enables comments template on pages
    # By default partals/docs/comments.html includes Disqus template
    # See https://gohugo.io/content-management/comments/#configure-disqus
    # Can be overwritten by same param in page frontmatter
    # BookComments = true
